import manifest from './brochureManifest.json'

const brochureManifest = manifest as Record<string, string[]>

// Set once the webp pages are uploaded to S3/CloudFront, e.g.
// BROCHURE_CDN_URL=https://d123abc.cloudfront.net/portfolio-brochures
const CDN_BASE = process.env.BROCHURE_CDN_URL?.replace(/\/$/, '')

// Reads the ordered .webp pages for a project's brochure folder from the manifest
// (generated by scripts/generate-brochure-manifest.js). Serves from CloudFront when
// BROCHURE_CDN_URL is set, otherwise from the local public/portfolio-brochures folder.
export function getBrochureImages(folder: string): string[] {
  const files = brochureManifest[folder]
  if (!files || files.length === 0) return []

  const base = CDN_BASE ?? '/portfolio-brochures'
  return files.map((f) => `${base}/${encodeURIComponent(folder)}/${encodeURIComponent(f)}`)
}
